version: "2"
services:
  node:
    image: "node:14-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - APP_PORT=8081
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"